# Generated by Django 3.1.7 on 2021-06-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('start_year', models.DateTimeField()),
                ('end_year', models.DateTimeField()),
            ],
        ),
    ]
