# Generated by Django 3.1.7 on 2021-06-22 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='end_year',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='start_year',
            new_name='start_date',
        ),
    ]
