# Generated by Django 3.1.7 on 2021-06-22 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_auto_20210622_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='titile',
            new_name='title',
        ),
    ]
