# Generated by Django 3.1.7 on 2021-06-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_auto_20210622_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
